### ISSUE TITLE
Data is reversed for Tx&Rx

### ISSUE THREAD

**Issue by atomicus** [natevw/node-nrf#28] opened 2015-01-28 19:54 UTC
I'm using node-rf on raspbery pi with nrf24l01 connected to arduino running on https://github.com/TMRh20/RF24/ library

In both cases - rx & tx data gests inverted.
When I receive, I need to reverse it so it can be displayed correctly as a string
When I transmit it, I need to reverse it before transmission so Arduino will receive it correctly.

**Comment by natevw** [comment] 2015-01-30 04:14
This is a dupe of https://github.com/natevw/node-nrf/issues/3 —I think the Arduino libraries are backwards according to the datasheet, but I'd like to at least add an option to deal with their backwards writes (perhaps even migrate to doing so by default at some point).

**Closed by natevw** 2015-01-30 04:14 UTC
